### ISSUE TITLE
Motion detection

### ISSUE THREAD

**Issue by thhart** [thhart/openhab2-addons#4]

**Comment by Roemer** [comment]
There is a home assistant plugin which supports motion, pir, sound, etc from axis cameras.
See: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/axis.py
At least for axis cameras, you could probably copy some work from there.
I guess other cameras use another system so maybe it makes sense to make this a dedicated Axis addon or to add a "CameraType" parameter somewhere to specify, what type of camera it is.

**Comment by thhart** [comment]
I don't like this proprietary stuff from each camera vendor, you will never know how reliable it is, the whole plugin is really meant as a generic one. I know the sensors and events from Axis and I recommend to use extra alarm triggers via HTTP/REST interfaces, I am not sure if openHab is supporting this already.

**Comment by Roemer** [comment]
I think setting your camera to send http messages on an event to OpenHab should already work.
The nice thing about this axis component in home assistant is that you do not need to setup anything in your camera.
