### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by Roemer** [thhart/openhab2-addons#5]
Just spent some time making it work correctly. Would be great to add some more information to the documentation:

# 1. Camera urls:
Axis uses: https://ip/jpg/image.jpg?resolution=640x480
or (I think the newer one): http://ip/axis-cgi/jpg/image.cgi?resolution=640x480
Also there is the resolution parameter to limit the resolution

# 2. Configuration
As the Paper-UI is still far from perfect, I wanted to configure everything in the conf files.
I ended up with this:
### Things
```
Thing camera:camera:6ebd867 "MyCam" [ urlUsername="user", urlPassword="pass", poll=5, urlSnapshot="http://ip/axis-cgi/jpg/image.cgi?resolution=640x480" ]
```
### Items:
```
Image Cam1 "MyCam" { channel="camera:camera:6ebd867:image" }
```
### Sitemap:
```
Image item=Cam1
```

**Comment by thhart** [comment]
Thanks a lot, can you let me know two things please:
1. For which UI is your manual config?
2. Which files exactly did you modify for this. I know this is basics but want to name them as well.

**Comment by Roemer** [comment]
I think the UI doesn't matter. The things and items should be for any UI.
I modified my *.things, *.items and *.sitemap files.
